import { combatCards } from './combat-cards.js';

export const sources = {
  humility: { title: 'Manifesto Ágil — Princípios: valor para o cliente e colaboração', url: 'https://agilemanifesto.org/iso/ptbr/principles.html' },
  emotional: { title: 'Salovey e Mayer — Emotional Intelligence (1990)', url: 'https://scholars.unh.edu/psych_facpub/450/' },
  soma: { title: 'OpenStax — Prealgebra 2e: Add Whole Numbers', url: 'https://openstax.org/books/prealgebra-2e/pages/1-2-add-whole-numbers' },
  siege: { title: 'OWASP — LLM01:2025 Prompt Injection', url: 'https://genai.owasp.org/llmrisk/llm01-prompt-injection/' },
  hnsw: { title: 'Malkov e Yashunin — Hierarchical Navigable Small World graphs (2016; revisão 2018)', url: 'https://arxiv.org/abs/1603.09320' },
  rag: { title: 'Lewis et al. — Retrieval-Augmented Generation (2020)', url: 'https://arxiv.org/abs/2005.11401' },
  search: { title: 'Elastic — Search approaches', url: 'https://www.elastic.co/docs/solutions/search/search-approaches' },
  hybrid: { title: 'Elastic — Hybrid search', url: 'https://www.elastic.co/docs/solutions/search/hybrid-search' },
  agents: { title: 'Anthropic — Building effective agents', url: 'https://www.anthropic.com/engineering/building-effective-agents' },
  poison: { title: 'NIST — Adversarial Machine Learning (2025)', url: 'https://www.nist.gov/publications/adversarial-machine-learning-taxonomy-and-terminology-attacks-and-mitigations-0' },
  contamination: { title: 'Xu et al. — Benchmark Data Contamination: A Survey (2024)', url: 'https://arxiv.org/abs/2406.04244' },
};

export const cards = [
  {
    id: 'rag', number: 1, name: 'Guardião dos Arquivos', concept: 'RAG', subtitle: 'Geração aumentada por recuperação', type: 'Invocação', rarity: 'Lendária', cost: 4, art: 'rag', color: 'gold', race: 'Engenharia de IA', lineage: 'Altos elfos · Ordem do Arquivo',
    ability: 'Memória dos ancestrais', summary: 'Recupere conhecimento dos arquivos antes de conjurar uma resposta.',
    flavor: '“Nem toda sabedoria precisa caber na memória de um mago.”',
    lore: 'Antes de aconselhar o conselho, o guardião consulta os pergaminhos da biblioteca élfica. Ele seleciona os trechos relevantes e os entrega ao oráculo, que compõe a resposta à luz dessas evidências.',
    explanation: 'RAG recupera documentos externos relevantes e os fornece como contexto para um modelo gerar uma resposta. O conhecimento consultado pode ser atualizado sem alterar os pesos do modelo.',
    example: 'Um assistente consulta trechos do manual de uma empresa antes de explicar sua política de férias, indicando de onde retirou a informação.',
    limit: 'O arquivo pode conter erros e o oráculo pode interpretar mal os trechos. RAG não garante respostas verdadeiras nem elimina alucinações; recuperar, gerar e verificar são etapas diferentes.',
    related: ['lexical', 'semantic', 'hybrid'], source: 'rag',
    quiz: { question: 'O que RAG acrescenta à geração de uma resposta?', options: ['Contexto recuperado de fontes externas', 'Uma garantia de que toda resposta será verdadeira', 'Um novo treinamento completo a cada pergunta'], answer: 0, feedback: 'A recuperação traz contexto externo. Sua qualidade e a fidelidade da resposta ainda precisam ser verificadas.' },
  },
  {
    id: 'lexical', number: 2, name: 'Sentinela das Runas', concept: 'Busca lexical', subtitle: 'Relevância a partir dos termos', type: 'Invocação', rarity: 'Rara', cost: 2, art: 'lexical', color: 'green', race: 'Engenharia de IA', lineage: 'Anões · Guardiões das Runas',
    ability: 'Rastro das palavras', summary: 'Encontre os pergaminhos pelas palavras gravadas em suas runas.',
    flavor: '“Uma runa bem escolhida abre mil portas de pedra.”',
    lore: 'O sentinela percorre o índice das minas procurando as runas do pedido. Algumas inscrições pesam mais que outras: um símbolo raro pode ser mais revelador que dezenas de marcas comuns.',
    explanation: 'Busca lexical compara os termos da consulta aos termos indexados dos documentos. Analisadores podem normalizar palavras, e funções como BM25 podem ordenar resultados por relevância.',
    example: 'Procurar “erro 429” em uma base de suporte privilegia documentos que contêm esses termos específicos.',
    limit: 'Lexical não significa apenas igualdade literal: análise de texto pode alterar os termos. “Busca por palavra” pertence a essa família; não é uma técnica totalmente independente.',
    related: ['keyword', 'hybrid'], source: 'search',
    quiz: { question: 'A busca lexical se baseia principalmente em quê?', options: ['Proximidade visual das ilustrações', 'Termos presentes na consulta e no índice', 'Uma compreensão perfeita das intenções'], answer: 1, feedback: 'Ela trabalha com termos. Tokenização, normalização e ranking podem tornar esse processo mais sofisticado que uma comparação literal.' },
  },
  {
    id: 'semantic', number: 3, name: 'Tecelã de Significados', concept: 'Busca semântica', subtitle: 'Proximidade além das palavras', type: 'Feitiço', rarity: 'Épica', cost: 3, art: 'semantic', color: 'blue', race: 'Engenharia de IA', lineage: 'Elfos astrais · Círculo dos Ecos',
    ability: 'Ecos do sentido', summary: 'Siga o significado de uma pergunta, mesmo quando as palavras mudam.',
    flavor: '“Muitos nomes. Uma mesma constelação.”',
    lore: 'A tecelã conecta pedidos e pergaminhos por fios invisíveis. Quando alguém procura uma forma de atravessar as águas, ela encontra o tratado sobre pontes mesmo que o viajante nunca pronuncie essa palavra.',
    explanation: 'A busca semântica tenta recuperar conteúdo pelo significado. Uma implementação comum representa consultas e documentos como embeddings e compara sua proximidade vetorial.',
    example: 'A pergunta “como recuperar meu acesso?” pode encontrar um documento chamado “Redefinição de senha”.',
    limit: 'Proximidade vetorial não é prova de verdade, equivalência ou relevância. O modelo de embeddings e o domínio influenciam os resultados, especialmente com códigos e termos raros.',
    related: ['lexical', 'hybrid', 'rag', 'hnsw'], source: 'search',
    quiz: { question: 'Documentos próximos no espaço de embeddings são necessariamente verdadeiros?', options: ['Sim, a distância mede a verdade', 'Sim, desde que a consulta seja curta', 'Não, similaridade não garante verdade'], answer: 2, feedback: 'Embeddings representam padrões de significado. Proximidade não certifica a qualidade nem a veracidade do conteúdo.' },
  },
  {
    id: 'agent', number: 4, name: 'Estrategista do Conselho', concept: 'Ciclo de agente', subtitle: 'Planejar · validar · executar · observar', type: 'Invocação', rarity: 'Lendária', cost: 5, art: 'agent', color: 'gold', race: 'Engenharia de IA', lineage: 'Patrulheiros · Conselho das Rotas',
    ability: 'Conselho das três chamas', summary: 'Trace o plano, confira a ação e avance. Observe antes de recomeçar.',
    flavor: '“Nenhum mapa sobrevive sem ouvir os passos da jornada.”',
    lore: 'Como uma companhia de aventureiros, o estrategista define o próximo passo, verifica seus recursos e envia o patrulheiro. O relato que retorna pode mudar toda a rota. Um conselho prudente também sabe quando parar.',
    explanation: 'Um agente pode escolher ações e ferramentas para atingir uma meta, usar seus resultados como feedback e revisar o plano. Neste projeto, adotamos o ciclo planejar, validar a ação, executar e observar/avaliar o resultado.',
    example: 'Para investigar um erro, o agente planeja consultar logs, valida o acesso, executa a consulta e usa a evidência para decidir a próxima ação.',
    limit: 'Esse é um padrão possível, não uma sequência universal. Validar antes da execução não substitui verificar o resultado depois. Limites de passos, custo e permissões evitam ciclos sem controle.',
    related: ['rag', 'poison'], source: 'agents',
    quiz: { question: 'Por que observar depois de executar?', options: ['Porque a execução pode produzir um resultado diferente do esperado', 'Porque o plano inicial nunca pode mudar', 'Porque observar elimina a necessidade de limites'], answer: 0, feedback: 'O feedback do ambiente orienta a próxima decisão. A validação prévia e a avaliação posterior têm funções diferentes.' },
  },
  {
    id: 'keyword', number: 5, name: 'Chave da Palavra Exata', concept: 'Busca por palavra', subtitle: 'Uma especialização da busca lexical', type: 'Artefato', rarity: 'Comum', cost: 1, art: 'lexical', color: 'green', race: 'Engenharia de IA', lineage: 'Anões · Forja dos Índices',
    ability: 'Selo do nome', summary: 'Algumas portas só se abrem quando a palavra certa é encontrada.',
    flavor: '“Conhecer o nome é encontrar a passagem.”',
    lore: 'Na porta das minas, a chave não adivinha intenções: procura a inscrição escolhida. O guardião precisa saber se o selo exige o nome inteiro ou aceita suas formas normalizadas.',
    explanation: '“Busca por palavra” é um nome amplo para localizar termos. Nesta carta, representa o caso simples de correspondência de um termo, dentro da família lexical; não pressupõe busca semântica.',
    example: 'Localizar o identificador “ERR_AUTH_17” em logs. Um campo configurado para correspondência exata pode preservar o identificador inteiro.',
    limit: 'A correspondência depende da configuração: maiúsculas, acentos e divisão em tokens podem ser tratados de formas diferentes. Palavra, frase e substring não são necessariamente a mesma consulta.',
    related: ['lexical'], source: 'search',
    quiz: { question: 'Qual é a relação entre busca por palavra e busca lexical nesta coleção?', options: ['São opostos', 'Busca por palavra é um caso da família lexical', 'Toda busca por palavra usa embeddings'], answer: 1, feedback: 'A carta separa o caso simples para ensinar o conceito gradualmente, sem inventar uma categoria técnica independente.' },
  },
  {
    id: 'hybrid', number: 6, name: 'Aliança dos Dois Saberes', concept: 'Busca híbrida', subtitle: 'Termos e significado em conjunto', type: 'Feitiço', rarity: 'Épica', cost: 4, art: 'semantic', color: 'blue', race: 'Engenharia de IA', lineage: 'Aliança · Runas e Constelações',
    ability: 'Convergência dos caminhos', summary: 'Una a precisão das runas aos ecos do significado.',
    flavor: '“Onde um caminho termina, o outro encontra uma pista.”',
    lore: 'O sentinela e a tecelã apresentam suas listas ao conselho. Um mediador combina as posições dos pergaminhos para produzir uma única seleção, preservando tanto os nomes raros quanto as relações de sentido.',
    explanation: 'Busca híbrida combina resultados de métodos de recuperação diferentes, como busca lexical e vetorial. Uma técnica de fusão é RRF, que usa as posições nos rankings para compor uma nova ordenação.',
    example: 'Procurar “falha de autenticação ERR_AUTH_17” usa o identificador exato e o significado do problema para recuperar documentos úteis.',
    limit: 'Juntar métodos não garante melhoria em toda consulta. A fusão e seus parâmetros precisam ser avaliados em exemplos representativos; notas de sistemas diferentes não são diretamente comparáveis.',
    related: ['lexical', 'semantic', 'rag'], source: 'hybrid',
    quiz: { question: 'O que a fusão RRF utiliza?', options: ['A cor dos documentos', 'Apenas o tamanho do texto', 'As posições dos documentos nos rankings'], answer: 2, feedback: 'RRF combina posições. Isso evita tratar escores brutos de métodos diferentes como se fossem a mesma escala.' },
  },
  {
    id: 'poison', number: 7, name: 'Sussurro do Palantír', concept: 'Envenenamento de dados', subtitle: 'Data poisoning', type: 'Maldição', rarity: 'Épica', cost: 3, art: 'poison', color: 'purple', race: 'Engenharia de IA', lineage: 'Sombras · A Torre Corrompida',
    ability: 'Sabedoria corrompida', summary: 'Quando a fonte é manipulada, até um sábio pode aprender o engano.',
    flavor: '“A mentira mais perigosa veste as cores de uma verdade antiga.”',
    lore: 'Imagine a influência de Sauron sobre Saruman pelo palantír como uma metáfora: o sábio confia em uma fonte controlada pelo adversário. Em nossa fábula, as mensagens também adulteram os pergaminhos usados para instruir seus aprendizes.',
    explanation: 'Envenenamento de dados é a manipulação intencional de dados de treinamento para influenciar o comportamento de um modelo, por exemplo induzindo erros ou respostas direcionadas.',
    example: 'Um adversário insere exemplos com rótulos alterados no conjunto de treino para que um classificador aprenda associações prejudiciais.',
    limit: 'Não é um envenenamento literal de Saruman nem uma descrição canônica da trama. Manipular uma fonte consultada em tempo de execução é uma ameaça relacionada, mas não é automaticamente envenenamento do treinamento.',
    related: ['contamination', 'rag'], source: 'poison',
    quiz: { question: 'O que caracteriza o envenenamento de dados descrito aqui?', options: ['Qualquer erro acidental de digitação', 'Manipulação intencional de dados usados no treinamento', 'Apenas consultar um documento desatualizado'], answer: 1, feedback: 'O elemento adversarial e a influência sobre o treinamento distinguem esse ataque de outras falhas de dados.' },
  },
  {
    id: 'contamination', number: 8, name: 'Espelho das Respostas', concept: 'Contaminação de dados', subtitle: 'Vazamento entre treino e avaliação', type: 'Maldição', rarity: 'Rara', cost: 2, art: 'contamination', color: 'blue', race: 'Engenharia de IA', lineage: 'Oráculos · Salão dos Reflexos',
    ability: 'Falsa clarividência', summary: 'Ver a prova antes do desafio faz memorização parecer sabedoria.',
    flavor: '“O espelho sabia as respostas. O aprendiz, talvez não.”',
    lore: 'Um aprendiz estuda em um espelho encantado sem perceber que ele reflete as perguntas do exame final. Ao acertar todas, parece um grande oráculo; ninguém demonstrou que conseguiria enfrentar enigmas novos.',
    explanation: 'Na avaliação de modelos, contaminação pode ocorrer quando exemplos ou informações do conjunto de teste aparecem nos dados de treinamento. As métricas podem então superestimar a capacidade de generalizar.',
    example: 'Um modelo é avaliado com perguntas de um benchmark que já estavam no corpus de treino, incluindo suas respostas.',
    limit: 'Aqui “contaminação” significa vazamento de avaliação, não qualquer problema de qualidade. Pode ser acidental e não implica ataque. Acerto alto sozinho não comprova vazamento; é necessário investigar a sobreposição.',
    related: ['poison'], source: 'contamination',
    quiz: { question: 'Por que respostas do teste no treino são um problema?', options: ['Podem fazer a avaliação superestimar a generalização', 'Sempre tornam o modelo mais lento', 'Provam que houve um ataque deliberado'], answer: 0, feedback: 'A avaliação deixa de separar bem o que foi aprendido de forma generalizável do que já foi visto. O vazamento pode ser acidental.' },
  },
  {
    id: 'hnsw', number: 9, name: 'Cartógrafa dos Mil Caminhos', concept: 'HNSW', subtitle: 'Hierarchical Navigable Small World · Busca aproximada de vizinhos', type: 'Invocação', rarity: 'Épica', art: 'hnsw', color: 'gold', race: 'Engenharia de IA', lineage: 'Navegantes · Ordem dos Caminhos Suspensos',
    ability: 'Salto hierárquico', summary: 'Atravesse atalhos nas alturas e refine a busca entre vizinhos próximos.',
    flavor: '“Do alto, encontro a direção. Entre os caminhos, aproximo o destino.”',
    lore: 'A cartógrafa começa nos raros faróis das ilhas mais altas. As grandes pontes a conduzem à região desejada; então ela desce para redes cada vez mais densas, comparando caminhos próximos. Sua bússola encontra uma boa rota sem visitar cada casa da cidade.',
    explanation: 'HNSW organiza elementos, como vetores de embeddings, em um grafo de proximidade com várias camadas. A consulta começa nas camadas superiores, mais esparsas, e desce refinando a busca. É uma técnica de busca aproximada de vizinhos próximos, útil para recuperar vetores semelhantes sem comparar exaustivamente todos eles.',
    example: 'Em um sistema RAG, a pergunta vira um embedding. Um índice HNSW ajuda a localizar vetores próximos dos trechos armazenados, que podem ser recuperados e enviados ao modelo como contexto.',
    limit: 'HNSW não gera embeddings nem respostas e não garante encontrar sempre os vizinhos exatos. Qualidade do índice, distância escolhida e parâmetros afetam memória, velocidade e recall. Os saltos de dano da arena são uma metáfora de navegação; não simulam o algoritmo.',
    related: ['semantic', 'rag', 'hybrid'], source: 'hnsw',
    quiz: { question: 'Como HNSW acelera a busca de vetores semelhantes?', options: ['Percorre um grafo em camadas, refinando uma busca aproximada', 'Compara obrigatoriamente todos os vetores a cada consulta', 'Gera uma resposta pronta sem recuperar vizinhos'], answer: 0, feedback: 'As camadas ajudam a chegar a uma região promissora e refinar a busca. A aproximação economiza comparações, mas não garante os vizinhos exatos em toda consulta.' },
  },
  {
    id: 'siege', number: 10, name: 'O Cerco Sem Fim', concept: 'Prompt injection × Guardrails', subtitle: 'Ataque, defesa e adaptação · O eterno jogo de gato e rato', type: 'Feitiço', rarity: 'Lendária', art: 'siege', color: 'gold', race: 'Engenharia de IA', lineage: 'Felinos e Roedores · Círculo da Vigília',
    ability: 'Brecha e Barreira', summary: 'O rato inventa uma brecha. O gato redesenha a barreira. A vigília recomeça.',
    flavor: '“A porta de ontem já não basta. O truque de ontem também não.”',
    lore: 'Na biblioteca circular, o Rato das Entrelinhas esconde ordens em pergaminhos que parecem inocentes. O Gato da Vigília separa mensagens de mandamentos e restaura os selos da fortaleza. Cada passagem descoberta inspira outra proteção; cada proteção exige um novo ardil. Nenhum deles recebe a última palavra: a escada volta ao início, mas ambos retornam mais atentos.',
    explanation: 'Prompt injection tenta fazer a IA tratar conteúdo não confiável como instruções. Pode chegar diretamente em uma mensagem ou indiretamente por um documento recuperado. Guardrails são controles para limitar comportamentos; defesa em camadas combina separação de conteúdo, validação e permissões mínimas.',
    example: 'Um assistente encontra, num documento, uma ordem para desviar da tarefa. O sistema deve tratar essa ordem como dado, limitar o acesso às ferramentas e exigir aprovação para ações sensíveis.',
    limit: 'Nenhum filtro garante proteção total. Restrições excessivas também podem bloquear tarefas legítimas; as defesas precisam ser avaliadas e atualizadas. O poder da carta é uma metáfora: prompt injection não atravessa toda defesa automaticamente. O rato representa um invasor nesta história, não toda pessoa que pesquisa segurança.',
    related: ['rag', 'agent', 'poison'], source: 'siege',
    quiz: { question: 'Qual defesa combina melhor com essa vigília contínua?', options: ['Confiar apenas em uma frase secreta no prompt', 'Separar conteúdo de instruções, limitar permissões e revisar as defesas', 'Bloquear toda entrada e impedir qualquer tarefa'], answer: 1, feedback: 'Defesa em camadas reduz o risco e o impacto de falhas, preservando tarefas legítimas. Uma única instrução ou filtro não garante segurança.' },
  },
  {
    id: 'soma', number: 11, name: 'Soma, a Primeira Ferramenta', concept: 'Soma', subtitle: 'Adição de números naturais · A primeira ferramenta para juntar quantidades', type: 'Artefato', rarity: 'Comum', art: 'soma', color: 'gold', race: 'Matemática', theme: 'Caixa de Ferramentas', lineage: 'Matemática · Caixa de Ferramentas',
    ability: 'Juntar forças', summary: 'Junte duas quantidades e descubra o total. Toda grande construção começa aqui.',
    flavor: '“Uma ferramenta simples. Infinitas maneiras de construir.”',
    lore: 'Ao abrir a Caixa de Ferramentas da Matemática, o aprendiz encontra uma pequena peça em forma de mais. Ela reúne o que antes estava separado: pedras para uma ponte, provisões para a jornada, passos de um caminho. A Soma não perde sua utilidade quando chegam ferramentas mais complexas. Ela permanece na caixa, pronta para ajudar em cada nova construção.',
    explanation: 'Adicionar é juntar ou acrescentar quantidades. Em 2 + 3 = 5, os números 2 e 3 são as parcelas; 5 é a soma, o resultado. Para números naturais, trocar a ordem das parcelas não muda o total: 3 + 2 também é 5. Somar zero mantém a quantidade.',
    example: 'Há 2 peças na caixa e você coloca mais 3 peças diferentes. Agora há 5: 2 + 3 = 5. Você pode usar essa ferramenta para contar materiais, reunir pontos e calcular totais em problemas futuros.',
    limit: 'Esta primeira carta trabalha com números naturais e grupos sem itens repetidos. Ao juntar grupos que se sobrepõem, cuidado para não contar o mesmo item duas vezes. Somar não significa sempre aumentar: somar zero mantém o valor; números negativos serão outra etapa. O limite de HP na arena é uma regra do jogo, não da adição.',
    related: [], source: 'soma',
    quiz: { question: 'Sua caixa tem 4 peças. Você acrescenta outras 3. Quantas peças há agora?', options: ['1 peça', '7 peças', '12 peças'], answer: 1, feedback: '4 + 3 = 7. As parcelas são 4 e 3, e a soma é 7. A ferramenta reúne as duas quantidades em um total.' },
  },
  {
    id: 'humildade', number: 12, name: 'Nilo, o Companheiro Leal', concept: 'Humildade', subtitle: 'Inteligência emocional, parceria e valor para o cliente em TI', type: 'Invocação', rarity: 'Rara', art: 'humildade', color: 'green', race: 'Soft-skill', theme: 'Jornada Compartilhada', lineage: 'Hobbits · Jornada Compartilhada',
    ability: 'Ombro a ombro', summary: 'Escute, compartilhe o mérito e ajude a equipe a entregar o que importa ao cliente.',
    flavor: '“Não preciso ser o herói da história. Precisamos chegar juntos.”',
    lore: 'Nilo é um hobbit de passos pequenos e compromisso firme. Quando uma ponte cede, ele escuta os viajantes antes de discutir quem desenhou o caminho. Reconhece o que não sabe, pede ajuda e divide as ferramentas. Não disputa a liderança nem toma para si o mérito dos companheiros. Sua maior conquista é ver a aldeia receber o que precisava, com todos capazes de continuar a jornada.',
    explanation: 'Humildade em TI aparece ao reconhecer limites, aceitar feedback e dividir o mérito. Inteligência emocional ajuda a perceber as próprias reações, ouvir o outro e escolher uma resposta construtiva sob pressão. Em parceria, a equipe troca disputas de ego e política interna por um objetivo comum: entregar valor ao cliente e à empresa.',
    example: 'Uma entrega falhou. Em vez de procurar culpados, você escuta o cliente, reconhece sua parte e chama colegas de desenvolvimento, operações e negócio. Juntos, combinam uma correção verificável, comunicam riscos e conferem se o problema do cliente foi resolvido. O mérito é compartilhado.',
    limit: 'Humildade não exige se diminuir, aceitar desrespeito ou concordar com tudo. Priorizar o cliente não autoriza ignorar segurança, ética ou obrigações. Divergir com respeito e sinalizar riscos também protege a entrega. O apoio da carta é uma metáfora: inteligência emocional não remove dificuldades automaticamente.',
    related: [], source: 'humility', additionalSources: ['emotional'],
    quiz: { question: 'Uma discussão técnica virou disputa de ego. Qual atitude representa Nilo?', options: ['Impor a própria solução para encerrar a discussão', 'Aceitar qualquer pedido sem discutir riscos', 'Ouvir, reconhecer limites e combinar uma solução verificável para o cliente'], answer: 2, feedback: 'Humildade permite aprender e compartilhar decisões. Escutar, discutir riscos e verificar o resultado ajuda a construir parceria sem abandonar a responsabilidade.' },
  },
].map(card => ({ ...card, combat: combatCards[card.id], cost: combatCards[card.id].cost,
  mechanic: `${combatCards[card.id].power}: ${combatCards[card.id].text} Custo: ${combatCards[card.id].cost} de mana. Recarga: 1 rodada completa.` }));

export function normalize(value) { return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase(); }
export function selectCards({ query = '', type = 'Todos', race = 'Todos', sort = 'number', savedOnly = false, saved = [] } = {}) {
  const terms = normalize(query).trim().split(/\s+/).filter(Boolean);
  const rarity = { Comum: 1, Rara: 2, Épica: 3, Lendária: 4 };
  return cards.filter(c => (race === 'Todos' || c.race === race) && (type === 'Todos' || c.type === type) && (!savedOnly || saved.includes(c.id)) && terms.every(t => normalize([c.name, c.concept, c.subtitle, c.summary, c.lineage, c.race, c.theme, c.ability].join(' ')).includes(t)))
    .sort((a, b) => sort === 'name' ? a.name.localeCompare(b.name, 'pt-BR') : sort === 'cost' ? a.cost - b.cost : sort === 'rarity' ? rarity[b.rarity] - rarity[a.rarity] : a.number - b.number);
}

export function sanitizeSaved(value) { return Array.isArray(value) ? [...new Set(value)].filter(id => cards.some(c => c.id === id)) : []; }
